name: Run Hello-World from py script
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: run hello world from python script
        run: python hello.py